x-veld:
  code:
    description:
    topic:
    additional:

    input:
      - volume: /veld/input/
        file_type:
        content:
        environemnt_var:

    output:
      - volume: /veld/output/
        file_type:
        content:
        environemnt_var:

    config:
      - environemnt_var:
        description:
        var_type:
        default:
        optional:

services:
  veld_wordembeddings_postgres_db:
    build: .
    #command: python /veld/code/REPLACE.py
    #user: root
    volumes:
      - ./src/:/veld/code/
      #- ./data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      #POSTGRES_USER: root

